package com.hirehop.core.domain.offline

internal val financeEntries: List<LexiconEntry> = listOf(
    tool("Tally", loose = listOf("tally erp", "tally erp 9", "tally prime", "tallyprime", "tally.erp 9")),
    skill("GST", "goods and services tax", loose = listOf("gstr")),
    skill("TDS"),
    skill("Income Tax", "itr", loose = listOf("income tax returns")),
    skill("Taxation", loose = listOf("tax filing")),
    skill("Accounting"),
    skill("Bookkeeping"),
    skill("Financial Accounting"),
    skill("Accounts Payable"),
    skill("Accounts Receivable"),
    skill("Reconciliation", "reconciliations"),
    skill("Bank Reconciliation", implies = listOf("reconciliation")),
    skill("Auditing", implies = listOf("audit"), loose = listOf("internal audit")),
    skill("Audit", implies = listOf("auditing")),
    skill("Financial Analysis"),
    skill("Financial Modelling", "financial modeling"),
    skill("Budgeting"),
    skill("Forecasting"),
    skill("Finance"),
    skill("MIS Reporting", "mis reports", "mis"),
    tool("SAP", "sap fico", "sap erp"),
    tool("QuickBooks"),
    tool("Zoho Books"),
    tool("ERP"),
    skill("Payroll"),
    skill("Invoicing"),
    skill("Billing", implies = listOf("invoicing")),
    skill("Cost Accounting", "costing"),
    skill("IFRS"),
    skill("Ind AS"),
)

internal val marketingEntries: List<LexiconEntry> = listOf(
    skill("SEO", "search engine optimization", "search engine optimisation"),
    skill("SEM"),
    tool("Google Analytics", "ga4"),
    tool("Google Ads", "google adwords", "adwords"),
    tool("Meta Ads", "facebook ads"),
    skill("Social Media Marketing", "smm"),
    skill("Social Media", implies = listOf("social media marketing")),
    skill("Digital Marketing"),
    skill("Content Writing", loose = listOf("content creation")),
    skill("Copywriting"),
    skill("Content Marketing"),
    skill("Email Marketing"),
    skill("Market Research"),
    skill("Brand Management"),
    skill("Branding", implies = listOf("brand management")),
    tool("HubSpot"),
    tool("Salesforce"),
    skill("CRM", "customer relationship management"),
    skill("Lead Generation"),
    skill("Cold Calling"),
    skill("Sales"),
    skill("B2B Sales", loose = listOf("b2b")),
    skill("Video Editing"),
    tool("Photoshop", "adobe photoshop"),
    tool("Canva"),
)

internal val operationsEntries: List<LexiconEntry> = listOf(
    skill("Supply Chain", "scm", loose = listOf("supply chain management")),
    skill("Logistics"),
    skill("Inventory Management"),
    skill("Procurement"),
    skill("Vendor Management"),
    skill("Process Improvement"),
    skill("Six Sigma"),
    skill("Operations Management"),
    skill("Data Entry"),
    skill("Customer Support", loose = listOf("customer service", "customer care")),
    skill("Project Management"),
    skill("Stakeholder Management"),
    tool("MS Office", "microsoft office", "office suite"),
    tool("PowerPoint", "ms powerpoint", "power point", "ppt"),
    skill("Documentation"),
)
