package com.hirehop.core.domain.offline

internal val languageEntries: List<LexiconEntry> = listOf(
    skill("Python", "python3", "python 3", "py"),
    skill("Java", loose = listOf("core java")),
    skill("Kotlin"),
    skill("C", loose = listOf("c programming", "c language")).copy(exactForms = listOf("C"), matchesCanonical = false),
    skill("C++", "cpp", "c plus plus"),
    skill("C#", "csharp", "c sharp"),
    skill(".NET", "dotnet", "dot net", loose = listOf(".net core")),
    tool("ASP.NET", implies = listOf(".net")),
    skill("JavaScript", "js", "java script", loose = listOf("ecmascript", "es6")),
    skill("TypeScript", "ts"),
    skill("Go", "golang", "go lang", loose = listOf("go programming", "go language")).copy(matchesCanonical = false),
    skill("Rust"),
    skill("PHP"),
    skill("Ruby"),
    skill("Swift", loose = listOf("swift programming", "swift language", "swiftui")).copy(
        exactForms = listOf("Swift"),
        matchesCanonical = false,
        blockedSuffixes = listOf("\\s+(?:resolution|response|delivery|action|turnaround|movement|growth)\\b"),
    ),
    skill("Scala"),
    skill("R", loose = listOf("r programming", "r language")).copy(exactForms = listOf("R"), matchesCanonical = false),
    skill("MATLAB"),
    skill("SQL", "structured query language"),
    skill("PL/SQL", "plsql", "pl sql", implies = listOf("sql")),
    skill("HTML", loose = listOf("html5")),
    skill("CSS", loose = listOf("css3")),
    skill("Bash", loose = listOf("bash scripting", "shell scripting", "shell script")),
)

internal val frameworkEntries: List<LexiconEntry> = listOf(
    tool("React", "react.js", "reactjs", "react js"),
    tool("React Native"),
    tool("Angular", loose = listOf("angularjs", "angular js")),
    tool("Vue", "vue.js", "vuejs", "vue js"),
    tool("Next.js", "nextjs"),
    tool("Node.js", "nodejs", "node js"),
    tool("Express").copy(aliases = listOf("express.js", "expressjs"), matchesCanonical = false),
    tool("Django"),
    tool("Flask"),
    tool("FastAPI"),
    tool("Spring Boot", "springboot"),
    tool("Spring", loose = listOf("spring framework")).copy(
        exactForms = listOf("Spring"),
        matchesCanonical = false,
        blockedSuffixes = listOf("\\s+(?:\\d{4}|intern\\w*|semester|break|season|term|batch)\\b"),
    ),
    tool("Hibernate"),
    tool("Bootstrap"),
    tool("Tailwind CSS", "tailwind"),
    tool("jQuery"),
    tool("Redux"),
    skill("Android", loose = listOf("android development", "android sdk")),
    tool("Android Studio", implies = listOf("android")),
    tool("Jetpack Compose", implies = listOf("android")),
    skill("iOS", loose = listOf("ios development")),
    tool("Flutter"),
    tool("Retrofit"),
    tool("Firebase"),
    skill("MVVM"),
    skill(
        "REST API",
        loose = listOf("restful api", "rest apis", "restful apis", "restful web services", "rest services"),
    ),
    skill("GraphQL"),
    skill("Microservices", loose = listOf("microservice")),
)

internal val engineeringPracticeEntries: List<LexiconEntry> = listOf(
    tool("Git"),
    tool("GitHub", implies = listOf("git")),
    tool("GitLab", implies = listOf("git")),
    tool("Docker"),
    tool("Kubernetes", "k8s"),
    tool("AWS", "amazon web services"),
    tool("Azure", "microsoft azure"),
    tool("GCP", "google cloud platform", loose = listOf("google cloud")),
    skill("CI/CD", "cicd", "ci cd", loose = listOf("continuous integration")),
    tool("Jenkins"),
    tool("Terraform"),
    tool("Linux", loose = listOf("unix")),
    skill("Agile"),
    skill("Scrum", implies = listOf("agile")),
    tool("Jira"),
    tool("Figma"),
    tool("Selenium"),
    tool("JUnit"),
    tool("Postman"),
    skill("Software Testing", loose = listOf("qa testing")),
    skill("Unit Testing", loose = listOf("unit tests"), implies = listOf("software testing")),
    skill("Manual Testing", implies = listOf("software testing")),
    skill("Test Automation", implies = listOf("software testing")),
    skill("Data Structures", loose = listOf("dsa", "data structures and algorithms")),
    skill("Algorithms"),
    skill("OOP", "object oriented programming", "oops"),
    skill("DBMS", "database management systems", loose = listOf("database management")),
    skill("Operating Systems"),
    skill("Computer Networks"),
    skill("System Design"),
    skill("Web Development", "web dev"),
    skill("Full Stack Development", implies = listOf("web development"), loose = listOf("full stack")),
    skill("Frontend Development", implies = listOf("web development")),
    skill("Backend Development", implies = listOf("web development")),
)
