version: 2
updates:
  - package-ecosystem: gradle
    directory: /
    schedule:
      interval: monthly
    open-pull-requests-limit: 3
    commit-message:
      prefix: build
      include: scope
    groups:
      kotlin-toolchain:
        patterns:
          - "org.jetbrains.kotlin*"
          - "com.google.devtools.ksp*"
      androidx:
        patterns:
          - "androidx.*"
      dagger-hilt:
        patterns:
          - "com.google.dagger*"

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
    open-pull-requests-limit: 3
    groups:
      github-actions:
        patterns:
          - "*"
    commit-message:
      prefix: ci
      include: scope
