package com.tailormyresume.core.domain.offline

internal val databaseEntries: List<LexiconEntry> = listOf(
    tool("MySQL", implies = listOf("sql")),
    tool("PostgreSQL", "postgres", implies = listOf("sql")),
    tool("MongoDB", "mongo"),
    tool("SQLite", implies = listOf("sql")),
    tool("Oracle Database", "oracle db"),
    tool("Redis"),
    skill("NoSQL"),
)

internal val analyticsEntries: List<LexiconEntry> = listOf(
    tool("Excel", "ms excel", "microsoft excel", loose = listOf("advanced excel")).copy(
        exactForms = listOf("Excel"),
        matchesCanonical = false,
        blockedSuffixes = listOf("\\s+(?:in|at|under)\\b"),
    ),
    tool("Google Sheets"),
    skill("VLOOKUP", "vlookups"),
    skill("Pivot Tables", "pivot table"),
    skill("VBA", loose = listOf("excel macros")),
    tool("Power BI", "powerbi", "microsoft power bi"),
    tool("Tableau"),
    tool("Looker"),
    tool("Power Query"),
    tool("Pandas"),
    tool("NumPy"),
    tool("Matplotlib"),
    tool("Scikit-learn", "sklearn"),
    tool("TensorFlow"),
    tool("PyTorch"),
    tool("Keras"),
    skill("Machine Learning", "ml"),
    skill("Deep Learning"),
    skill("NLP", "natural language processing"),
    skill("Computer Vision"),
    skill("Artificial Intelligence", "ai"),
    skill("Generative AI", "genai", "gen ai"),
    skill("Data Analysis", loose = listOf("data analytics")),
    skill("Data Science"),
    skill("Data Visualization", "data visualisation"),
    skill("Statistics", loose = listOf("statistical analysis")),
    skill("ETL"),
    tool("Apache Spark").copy(
        exactForms = listOf("Spark"),
        blockedSuffixes = listOf("\\s+(?:interest|curiosity|joy|creativity|innovation|passion|ideas?)\\b"),
    ),
    tool("PySpark", implies = listOf("apache spark")),
    tool("Hadoop"),
    tool("Kafka", "apache kafka"),
    tool("Airflow", "apache airflow"),
    skill("Big Data"),
)
