name: delivery-gates
on:
  pull_request:
    types: [opened, synchronize, reopened, edited]
permissions:
  contents: read
jobs:
  pregate:
    name: delivery-gates-pregate
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1
        with:
          fetch-depth: 0
      - uses: BengaluruBuilders/delivery-gates@ba9da168b514abe4c7e70d66de3be47470a9aa1a
